// Code generated by controller-gen. DO NOT EDIT.

package internal

import (
	fmt "fmt"
	sync "sync"

	typed "sigs.k8s.io/structured-merge-diff/v6/typed"
)

func Parser() *typed.Parser {
	parserOnce.Do(func() {
		var err error
		parser, err = typed.NewParser(schemaYAML)
		if err != nil {
			panic(fmt.Sprintf("Failed to parse schema: %v", err))
		}
	})
	return parser
}

var parserOnce sync.Once
var parser *typed.Parser
var schemaYAML = typed.YAMLObject(`types:
- name: com.github.helmetica-framework.custos.api.v1.Arcanum
  map:
    fields:
    - name: apiVersion
      type:
        scalar: string
    - name: kind
      type:
        scalar: string
    - name: metadata
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta
    - name: spec
      type:
        namedType: com.github.helmetica-framework.custos.api.v1.ArcanumSpec
    - name: status
      type:
        namedType: com.github.helmetica-framework.custos.api.v1.ArcanumStatus
- name: com.github.helmetica-framework.custos.api.v1.ArcanumPhase
  scalar: string
- name: com.github.helmetica-framework.custos.api.v1.ArcanumSpec
  map:
    fields:
    - name: credentials
      type:
        namedType: com.github.helmetica-framework.custos.api.v1.CredentialsSpec
    - name: suspend
      type:
        scalar: boolean
    - name: target
      type:
        namedType: com.github.helmetica-framework.custos.api.v1.TargetSpec
- name: com.github.helmetica-framework.custos.api.v1.ArcanumStatus
  map:
    fields:
    - name: gatherJobName
      type:
        scalar: string
    - name: gatheredHash
      type:
        scalar: string
    - name: message
      type:
        scalar: string
    - name: observedGeneration
      type:
        scalar: numeric
    - name: phase
      type:
        namedType: com.github.helmetica-framework.custos.api.v1.ArcanumPhase
    - name: secretName
      type:
        scalar: string
    - name: secretNamespace
      type:
        scalar: string
- name: com.github.helmetica-framework.custos.api.v1.CredentialsSpec
  map:
    fields:
    - name: valueMapping
      type:
        map:
          elementType:
            namedType: com.github.helmetica-framework.custos.api.v1.ValueSource
- name: com.github.helmetica-framework.custos.api.v1.SourceType
  scalar: string
- name: com.github.helmetica-framework.custos.api.v1.TargetSpec
  map:
    fields:
    - name: name
      type:
        scalar: string
- name: com.github.helmetica-framework.custos.api.v1.ValueSource
  map:
    fields:
    - name: apiVersion
      type:
        scalar: string
      default: v1
    - name: command
      type:
        list:
          elementType:
            scalar: string
          elementRelationship: atomic
    - name: container
      type:
        scalar: string
    - name: key
      type:
        scalar: string
    - name: kind
      type:
        scalar: string
    - name: name
      type:
        scalar: string
    - name: path
      type:
        scalar: string
    - name: podSelector
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.LabelSelector
    - name: podWait
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.Duration
    - name: source
      type:
        namedType: com.github.helmetica-framework.custos.api.v1.SourceType
    - name: value
      type:
        scalar: string
- name: io.k8s.apimachinery.pkg.apis.meta.v1.Duration
  scalar: string
- name: io.k8s.apimachinery.pkg.apis.meta.v1.FieldsV1
  map:
    elementType:
      scalar: untyped
      list:
        elementType:
          namedType: __untyped_atomic_
        elementRelationship: atomic
      map:
        elementType:
          namedType: __untyped_deduced_
        elementRelationship: separable
- name: io.k8s.apimachinery.pkg.apis.meta.v1.LabelSelector
  map:
    fields:
    - name: matchExpressions
      type:
        list:
          elementType:
            namedType: io.k8s.apimachinery.pkg.apis.meta.v1.LabelSelectorRequirement
          elementRelationship: atomic
    - name: matchLabels
      type:
        map:
          elementType:
            scalar: string
    elementRelationship: atomic
- name: io.k8s.apimachinery.pkg.apis.meta.v1.LabelSelectorOperator
  scalar: string
- name: io.k8s.apimachinery.pkg.apis.meta.v1.LabelSelectorRequirement
  map:
    fields:
    - name: key
      type:
        scalar: string
    - name: operator
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.LabelSelectorOperator
    - name: values
      type:
        list:
          elementType:
            scalar: string
          elementRelationship: atomic
- name: io.k8s.apimachinery.pkg.apis.meta.v1.ManagedFieldsEntry
  map:
    fields:
    - name: apiVersion
      type:
        scalar: string
    - name: fieldsType
      type:
        scalar: string
    - name: fieldsV1
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.FieldsV1
    - name: manager
      type:
        scalar: string
    - name: operation
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.ManagedFieldsOperationType
    - name: subresource
      type:
        scalar: string
    - name: time
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.Time
- name: io.k8s.apimachinery.pkg.apis.meta.v1.ManagedFieldsOperationType
  scalar: string
- name: io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta
  map:
    fields:
    - name: annotations
      type:
        map:
          elementType:
            scalar: string
    - name: creationTimestamp
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.Time
    - name: deletionGracePeriodSeconds
      type:
        scalar: numeric
    - name: deletionTimestamp
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.Time
    - name: finalizers
      type:
        list:
          elementType:
            scalar: string
          elementRelationship: associative
    - name: generateName
      type:
        scalar: string
    - name: generation
      type:
        scalar: numeric
    - name: labels
      type:
        map:
          elementType:
            scalar: string
    - name: managedFields
      type:
        list:
          elementType:
            namedType: io.k8s.apimachinery.pkg.apis.meta.v1.ManagedFieldsEntry
          elementRelationship: atomic
    - name: name
      type:
        scalar: string
    - name: namespace
      type:
        scalar: string
    - name: ownerReferences
      type:
        list:
          elementType:
            namedType: io.k8s.apimachinery.pkg.apis.meta.v1.OwnerReference
          elementRelationship: associative
          keys:
          - uid
    - name: resourceVersion
      type:
        scalar: string
    - name: selfLink
      type:
        scalar: string
    - name: uid
      type:
        namedType: io.k8s.apimachinery.pkg.types.UID
- name: io.k8s.apimachinery.pkg.apis.meta.v1.OwnerReference
  map:
    fields:
    - name: apiVersion
      type:
        scalar: string
    - name: blockOwnerDeletion
      type:
        scalar: boolean
    - name: controller
      type:
        scalar: boolean
    - name: kind
      type:
        scalar: string
    - name: name
      type:
        scalar: string
    - name: uid
      type:
        namedType: io.k8s.apimachinery.pkg.types.UID
    elementRelationship: atomic
- name: io.k8s.apimachinery.pkg.apis.meta.v1.Time
  scalar: untyped
- name: io.k8s.apimachinery.pkg.types.UID
  scalar: string
- name: __untyped_atomic_
  scalar: untyped
  list:
    elementType:
      namedType: __untyped_atomic_
    elementRelationship: atomic
  map:
    elementType:
      namedType: __untyped_atomic_
    elementRelationship: atomic
- name: __untyped_deduced_
  scalar: untyped
  list:
    elementType:
      namedType: __untyped_atomic_
    elementRelationship: atomic
  map:
    elementType:
      namedType: __untyped_deduced_
    elementRelationship: separable
`)
