// Code generated by controller-gen. DO NOT EDIT.

package v1

// ArcanumSpecApplyConfiguration represents a declarative configuration of the ArcanumSpec type for use
// with apply.
//
// ArcanumSpec describes one Secret custos assembles: where every value comes
// from, and what the Secret is called.
type ArcanumSpecApplyConfiguration struct {
	// Suspend pauses reconciliation. A suspended arcanum holds at Pending and
	// custos leaves everything it owns untouched, which is the escape hatch
	// when the controller and the cluster disagree.
	Suspend *bool `json:"suspend,omitempty"`
	// Target names the Secret. It is required because a Secret custos cannot
	// name is a Secret nobody can consume.
	Target *TargetSpecApplyConfiguration `json:"target,omitempty"`
	// Credentials holds the value mapping. An arcanum with none is legal and
	// produces an empty Secret, which is how a chart can declare the Secret
	// before it knows what goes in it.
	Credentials *CredentialsSpecApplyConfiguration `json:"credentials,omitempty"`
}

// ArcanumSpecApplyConfiguration constructs a declarative configuration of the ArcanumSpec type for use with
// apply.
func ArcanumSpec() *ArcanumSpecApplyConfiguration {
	return &ArcanumSpecApplyConfiguration{}
}

// WithSuspend sets the Suspend field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Suspend field is set to the value of the last call.
func (b *ArcanumSpecApplyConfiguration) WithSuspend(value bool) *ArcanumSpecApplyConfiguration {
	b.Suspend = &value
	return b
}

// WithTarget sets the Target field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Target field is set to the value of the last call.
func (b *ArcanumSpecApplyConfiguration) WithTarget(value *TargetSpecApplyConfiguration) *ArcanumSpecApplyConfiguration {
	b.Target = value
	return b
}

// WithCredentials sets the Credentials field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Credentials field is set to the value of the last call.
func (b *ArcanumSpecApplyConfiguration) WithCredentials(value *CredentialsSpecApplyConfiguration) *ArcanumSpecApplyConfiguration {
	b.Credentials = value
	return b
}
