// Code generated by controller-gen. DO NOT EDIT.

package v1

// ArcanumSpecApplyConfiguration represents a declarative configuration of the ArcanumSpec type for use
// with apply.
//
// ArcanumSpec describes what custos guards. It is deliberately near-empty: the
// real fields land here once the resource custos watches over is settled.
type ArcanumSpecApplyConfiguration struct {
	// Suspend pauses reconciliation. A suspended arcanum holds at Pending and
	// custos leaves everything it owns untouched, which is the escape hatch
	// when the controller and the cluster disagree.
	Suspend *bool `json:"suspend,omitempty"`
}

// ArcanumSpecApplyConfiguration constructs a declarative configuration of the ArcanumSpec type for use with
// apply.
func ArcanumSpec() *ArcanumSpecApplyConfiguration {
	return &ArcanumSpecApplyConfiguration{}
}

// WithSuspend sets the Suspend field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Suspend field is set to the value of the last call.
func (b *ArcanumSpecApplyConfiguration) WithSuspend(value bool) *ArcanumSpecApplyConfiguration {
	b.Suspend = &value
	return b
}
