// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	apiv1 "github.com/helmetica-framework/custos/api/v1"
)

// ArcanumStatusApplyConfiguration represents a declarative configuration of the ArcanumStatus type for use
// with apply.
type ArcanumStatusApplyConfiguration struct {
	Phase *apiv1.ArcanumPhase `json:"phase,omitempty"`
	// ObservedGeneration is the spec generation the phase was computed from.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`
	// Message explains a Pending or Failed phase.
	Message *string `json:"message,omitempty"`
}

// ArcanumStatusApplyConfiguration constructs a declarative configuration of the ArcanumStatus type for use with
// apply.
func ArcanumStatus() *ArcanumStatusApplyConfiguration {
	return &ArcanumStatusApplyConfiguration{}
}

// WithPhase sets the Phase field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Phase field is set to the value of the last call.
func (b *ArcanumStatusApplyConfiguration) WithPhase(value apiv1.ArcanumPhase) *ArcanumStatusApplyConfiguration {
	b.Phase = &value
	return b
}

// WithObservedGeneration sets the ObservedGeneration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservedGeneration field is set to the value of the last call.
func (b *ArcanumStatusApplyConfiguration) WithObservedGeneration(value int64) *ArcanumStatusApplyConfiguration {
	b.ObservedGeneration = &value
	return b
}

// WithMessage sets the Message field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Message field is set to the value of the last call.
func (b *ArcanumStatusApplyConfiguration) WithMessage(value string) *ArcanumStatusApplyConfiguration {
	b.Message = &value
	return b
}
