// Code generated by controller-gen. DO NOT EDIT.

package v1

// CredentialsSpecApplyConfiguration represents a declarative configuration of the CredentialsSpec type for use
// with apply.
//
// CredentialsSpec holds the mapping. Every entry becomes a key in the target
// Secret.
type CredentialsSpecApplyConfiguration struct {
	// ValueMapping is keyed by the Secret key to produce. Consumers read these
	// names, so they are the chart author's to choose, not derived from
	// wherever the value happened to come from.
	ValueMapping map[string]ValueSourceApplyConfiguration `json:"valueMapping,omitempty"`
}

// CredentialsSpecApplyConfiguration constructs a declarative configuration of the CredentialsSpec type for use with
// apply.
func CredentialsSpec() *CredentialsSpecApplyConfiguration {
	return &CredentialsSpecApplyConfiguration{}
}

// WithValueMapping puts the entries into the ValueMapping field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the ValueMapping field,
// overwriting an existing map entries in ValueMapping field with the same key.
func (b *CredentialsSpecApplyConfiguration) WithValueMapping(entries map[string]ValueSourceApplyConfiguration) *CredentialsSpecApplyConfiguration {
	if b.ValueMapping == nil && len(entries) > 0 {
		b.ValueMapping = make(map[string]ValueSourceApplyConfiguration, len(entries))
	}
	for k, v := range entries {
		b.ValueMapping[k] = v
	}
	return b
}
