// Code generated by controller-gen. DO NOT EDIT.

package v1

// TargetSpecApplyConfiguration represents a declarative configuration of the TargetSpec type for use
// with apply.
//
// TargetSpec names the Secret. The namespace is not settable: it follows from
// whether the Arcanum's own namespace carries chryso's claim annotation, so a
// reagent chart works both under chrysopoeia and under a plain helm install.
type TargetSpecApplyConfiguration struct {
	// Name is the Secret's name in whichever namespace the placement rule
	// picks.
	Name *string `json:"name,omitempty"`
}

// TargetSpecApplyConfiguration constructs a declarative configuration of the TargetSpec type for use with
// apply.
func TargetSpec() *TargetSpecApplyConfiguration {
	return &TargetSpecApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *TargetSpecApplyConfiguration) WithName(value string) *TargetSpecApplyConfiguration {
	b.Name = &value
	return b
}
