// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	apiv1 "github.com/helmetica-framework/custos/api/v1"
	apismetav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	metav1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// ValueSourceApplyConfiguration represents a declarative configuration of the ValueSource type for use
// with apply.
//
// ValueSource says where one key's value comes from. It is flat rather than a
// union of sub-structs because a chart author has to write this by hand, and
// the CEL rules below keep the wrong combinations out.
type ValueSourceApplyConfiguration struct {
	// Source decides which of the fields below custos reads. There is no
	// default: guessing from which fields are set would turn a typo into a
	// different lookup.
	Source *apiv1.SourceType `json:"source,omitempty"`
	// Value is the literal for a const source, or the template body for a
	// template source.
	Value *string `json:"value,omitempty"`
	// APIVersion is the group and version of an objectRef's target. It
	// defaults to the core group, since most references are to a Secret or a
	// ConfigMap.
	APIVersion *string `json:"apiVersion,omitempty"`
	// Kind is the kind of an objectRef's target.
	Kind *string `json:"kind,omitempty"`
	// Name is the object's name. It is rendered against the metadata context
	// first, so "{{.ClaimName}}-app" works.
	Name *string `json:"name,omitempty"`
	// Key reads one entry out of a Secret's or ConfigMap's data. A Secret's
	// value is decoded.
	Key *string `json:"key,omitempty"`
	// Path is a JSONPath, used by objectRef for anything that is not a Secret
	// or ConfigMap data key, and by claimParam against the claim.
	Path *string `json:"path,omitempty"`
	// PodSelector picks the pod an exec source runs in. It is a selector
	// rather than a name because pod names are generated and change on every
	// restart.
	PodSelector *metav1.LabelSelectorApplyConfiguration `json:"podSelector,omitempty"`
	// Container is which one to run in. Left empty, the pod's
	// kubectl.kubernetes.io/default-container annotation decides, and failing
	// that its first container.
	//
	// The API server only defaults this itself when the pod has exactly one
	// container, so for anything with a sidecar the choice has to be made
	// before the request goes out.
	Container *string `json:"container,omitempty"`
	// PodWait is how long to wait for a pod matching PodSelector to become
	// ready before failing the gather. It exists because a service that is
	// slow to start is the ordinary case, not a fault, and waiting inside one
	// attempt is cheaper than failing and being retried.
	//
	// Unset falls back to the gather binary's own default. Changing it moves
	// the plan hash, so it re-runs a gather that has already settled.
	PodWait *apismetav1.Duration `json:"podWait,omitempty"`
	// Command's arguments are rendered against the metadata context.
	//
	// It must be idempotent: safe to run any number of times, returning the
	// same value each time. A gather is retried until it succeeds, so a command
	// that mints a fresh password per run would rewrite the target Secret under
	// consumers that have already read it. Provisioning is fine as long as it
	// is written to survive repetition.
	Command []string `json:"command,omitempty"`
}

// ValueSourceApplyConfiguration constructs a declarative configuration of the ValueSource type for use with
// apply.
func ValueSource() *ValueSourceApplyConfiguration {
	return &ValueSourceApplyConfiguration{}
}

// WithSource sets the Source field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Source field is set to the value of the last call.
func (b *ValueSourceApplyConfiguration) WithSource(value apiv1.SourceType) *ValueSourceApplyConfiguration {
	b.Source = &value
	return b
}

// WithValue sets the Value field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Value field is set to the value of the last call.
func (b *ValueSourceApplyConfiguration) WithValue(value string) *ValueSourceApplyConfiguration {
	b.Value = &value
	return b
}

// WithAPIVersion sets the APIVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the APIVersion field is set to the value of the last call.
func (b *ValueSourceApplyConfiguration) WithAPIVersion(value string) *ValueSourceApplyConfiguration {
	b.APIVersion = &value
	return b
}

// WithKind sets the Kind field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kind field is set to the value of the last call.
func (b *ValueSourceApplyConfiguration) WithKind(value string) *ValueSourceApplyConfiguration {
	b.Kind = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *ValueSourceApplyConfiguration) WithName(value string) *ValueSourceApplyConfiguration {
	b.Name = &value
	return b
}

// WithKey sets the Key field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Key field is set to the value of the last call.
func (b *ValueSourceApplyConfiguration) WithKey(value string) *ValueSourceApplyConfiguration {
	b.Key = &value
	return b
}

// WithPath sets the Path field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Path field is set to the value of the last call.
func (b *ValueSourceApplyConfiguration) WithPath(value string) *ValueSourceApplyConfiguration {
	b.Path = &value
	return b
}

// WithPodSelector sets the PodSelector field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PodSelector field is set to the value of the last call.
func (b *ValueSourceApplyConfiguration) WithPodSelector(value *metav1.LabelSelectorApplyConfiguration) *ValueSourceApplyConfiguration {
	b.PodSelector = value
	return b
}

// WithContainer sets the Container field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Container field is set to the value of the last call.
func (b *ValueSourceApplyConfiguration) WithContainer(value string) *ValueSourceApplyConfiguration {
	b.Container = &value
	return b
}

// WithPodWait sets the PodWait field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PodWait field is set to the value of the last call.
func (b *ValueSourceApplyConfiguration) WithPodWait(value apismetav1.Duration) *ValueSourceApplyConfiguration {
	b.PodWait = &value
	return b
}

// WithCommand adds the given value to the Command field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Command field.
func (b *ValueSourceApplyConfiguration) WithCommand(values ...string) *ValueSourceApplyConfiguration {
	for i := range values {
		b.Command = append(b.Command, values[i])
	}
	return b
}
