// Code generated by controller-gen. DO NOT EDIT.

package applyconfiguration

import (
	v1 "github.com/helmetica-framework/custos/api/v1"
	apiv1 "github.com/helmetica-framework/custos/applyconfiguration/api/v1"
	internal "github.com/helmetica-framework/custos/applyconfiguration/internal"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	managedfields "k8s.io/apimachinery/pkg/util/managedfields"
)

// ForKind returns an apply configuration type for the given GroupVersionKind, or nil if no
// apply configuration type exists for the given GroupVersionKind.
func ForKind(kind schema.GroupVersionKind) interface{} {
	switch kind {
	// Group=arcana.helmetica.io, Version=v1
	case v1.SchemeGroupVersion.WithKind("Arcanum"):
		return &apiv1.ArcanumApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("ArcanumSpec"):
		return &apiv1.ArcanumSpecApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("ArcanumStatus"):
		return &apiv1.ArcanumStatusApplyConfiguration{}

	}
	return nil
}

func NewTypeConverter(scheme *runtime.Scheme) managedfields.TypeConverter {
	return managedfields.NewSchemeTypeConverter(scheme, internal.Parser())
}
