---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - arcana.helmetica.io
  resources:
  - arcana
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - arcana.helmetica.io
  resources:
  - arcana/finalizers
  verbs:
  - update
- apiGroups:
  - arcana.helmetica.io
  resources:
  - arcana/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - events.k8s.io
  resources:
  - events
  verbs:
  - create
  - patch
