apiVersion: arcana.helmetica.io/v1
kind: Arcanum
metadata:
  name: sample
spec:
  target:
    name: sample-credentials
  credentials:
    valueMapping:
      HOST:
        source: const
        value: sample-rw
      PORT:
        source: const
        value: "5432"
      URL:
        source: template
        value: "postgres://{{.HOST}}:{{.PORT}}/sample"
